import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const dictionary = {

  "Users Management": "إدارة المستخدمين",
  "Services Management": "إدارة الخدمات",
  "Projects Management": "إدارة المشاريع",
  "Orders & Contracts": "الطلبات والعقود",
  "Manage clients and freelancers accounts": "إدارة حسابات العملاء والمستقلين",
  "Manage freelancer services": "إدارة خدمات المستقلين",
  "Manage client projects and freelancers": "إدارة مشاريع العملاء والمستقلين",
  "Track projects, orders and contracts": "متابعة المشاريع والطلبات والعقود",
  "Manage freelancer paid subscriptions": "إدارة الاشتراكات المدفوعة للمستقلين",
  "Monitor payments and platform commissions": "مراقبة المدفوعات وعمولات المنصة",
  "Manage complaints and reported issues": "إدارة الشكاوى والمشكلات المبلّغ عنها",
  "Monitor ratings and user comments": "مراقبة التقييمات وتعليقات المستخدمين",
  "+ Add User": "+ إضافة مستخدم",
  "+ Add Service": "+ إضافة خدمة",
  "+ Add Project": "+ إضافة مشروع",
  "+ Add Subscription": "+ إضافة اشتراك",
  "User": "المستخدم",
  "Service": "الخدمة",
  "Freelancer": "المستقل",
  "Client": "العميل",
  "Email": "البريد الإلكتروني",
  "Account Type": "نوع الحساب",
  "Category": "التصنيف",
  "Price": "السعر",
  "Delivery": "التسليم",
  "Delivery Time": "مدة التسليم",
  "Service Name": "اسم الخدمة",
  "Project": "المشروع",
  "Budget": "الميزانية",
  "Deadline": "الموعد النهائي",
  "Offers": "العروض",
  "Project Title": "عنوان المشروع",
  "Number of Offers": "عدد العروض",
  "Selected Freelancer": "المستقل المختار",
  "Order": "الطلب",
  "Order Number": "رقم الطلب",
  "Value": "القيمة",
  "Commission": "العمولة",
  "Payment": "الدفع",
  "Project Value": "قيمة المشروع",
  "Payment Status": "حالة الدفع",
  "Track": "تتبع",
  "Plan": "الخطة",
  "Start": "البداية",
  "End": "النهاية",
  "Subscription Plan": "خطة الاشتراك",
  "Start Date": "تاريخ البداية",
  "End Date": "تاريخ الانتهاء",
  "Transaction": "المعاملة",
  "Amount": "المبلغ",
  "Freelancer Due": "مستحقات المستقل",
  "Transfer": "التحويل",
  "Transaction Number": "رقم المعاملة",
  "Gross Amount": "المبلغ الإجمالي",
  "Platform Commission": "عمولة المنصة",
  "Transaction Date": "تاريخ المعاملة",
  "Transfer Status": "حالة التحويل",
  "Report": "البلاغ",
  "Problem Type": "نوع المشكلة",
  "Reporter": "المبلّغ",
  "Other Party": "الطرف الآخر",
  "Description": "الوصف",
  "Date": "التاريخ",
  "Report Number": "رقم البلاغ",
  "Report Date": "تاريخ البلاغ",
  "Resolve": "حل البلاغ",
  "Reviewer": "المقيّم",
  "Rating": "التقييم",
  "Comment": "التعليق",
  "Service": "الخدمة",
  "Subscription": "الاشتراك",
  "Subscriptions": "الاشتراكات",
  "Total Orders": "إجمالي الطلبات",
  "Reviews": "التقييمات",
  "Edit": "تعديل",
  "Add": "إضافة",
  "Add Users Management": "إضافة مستخدم",
  "Add Services Management": "إضافة خدمة",
  "Add Projects Management": "إضافة مشروع",
  "Add Subscriptions": "إضافة اشتراك",
  "Home": "الرئيسية",
  "Dashboard": "لوحة التحكم",
  "Users Management": "إدارة المستخدمين",
  "Services Management": "إدارة الخدمات",
  "Projects Management": "إدارة المشاريع",
  "Orders & Contracts": "الطلبات والعقود",
  "Subscriptions": "الاشتراكات",
  "Total Orders": "إجمالي الطلبات",
  "Reviews": "التقييمات",
  "Payments & Commissions": "المدفوعات والعمولات",
  "Reports & Disputes": "البلاغات والنزاعات",
  "Reviews & Comments": "التقييمات والتعليقات",
  "Statistics": "الإحصائيات",
  "Profile & Settings": "الملف الشخصي والإعدادات",
  "Workspace & Management": "مساحة العمل والإدارة",
  "Admin Panel": "لوحة الأدمن",
  "Administrator": "مدير النظام",
  "Search...": "بحث...",
  "Search users...": "البحث عن المستخدمين...",
  "Search services...": "البحث عن الخدمات...",
  "Search projects...": "البحث عن المشاريع...",
  "Search orders...": "البحث عن الطلبات...",
  "Search subscriptions...": "البحث عن الاشتراكات...",
  "Search payments...": "البحث عن المدفوعات...",
  "Search reports...": "البحث عن البلاغات...",
  "Search reviews...": "البحث عن التقييمات...",
  "All": "الكل",
  "Active": "نشط",
  "Inactive": "غير نشط",
  "Blocked": "محظور",
  "Pending": "قيد الانتظار",
  "In Progress": "قيد التنفيذ",
  "Completed": "مكتمل",
  "Cancelled": "ملغى",
  "Paid": "مدفوع",
  "Refunded": "مُسترد",
  "Expired": "منتهي",
  "Published": "منشور",
  "Flagged": "مُبلّغ عنه",
  "In Review": "قيد المراجعة",
  "Resolved": "تم الحل",
  "Transferred": "تم التحويل",
  "View": "عرض",
  "Edit": "تعديل",
  "Delete": "حذف",
  "Cancel": "إلغاء",
  "Save Changes": "حفظ التغييرات",
  "Add": "إضافة",
  "Track": "تتبع",
  "Resolve": "حل البلاغ",
  "Actions": "الإجراءات",
  "No results found": "لم يتم العثور على نتائج",
  "Showing": "عرض",
  "of": "من",
  "records": "سجلات",
  "Details": "التفاصيل",
  "Complete the information below": "أكمل المعلومات أدناه",
  "View information": "عرض المعلومات",
  "Platform Growth": "نمو المنصة",
  "Projects and revenue overview": "نظرة عامة على المشاريع والإيرادات",
  "Project Status": "حالة المشاريع",
  "Current distribution": "التوزيع الحالي",
  "Top Categories": "أكثر التصنيفات نشاطاً",
  "Most active service categories": "أكثر تصنيفات الخدمات نشاطاً",
  "Total Users": "إجمالي المستخدمين",
  "Total Projects": "إجمالي المشاريع",
  "Total Revenue": "إجمالي الإيرادات",
  "Pending Reports": "البلاغات المعلقة",
  "Needs review": "تحتاج مراجعة",
  "Completed": "مكتملة",
  "Pending": "معلقة",
  "In Progress": "قيد التنفيذ",
  "Jan": "يناير",
  "Feb": "فبراير",
  "Mar": "مارس",
  "Apr": "أبريل",
  "May": "مايو",
  "Jun": "يونيو",
  "Jul": "يوليو",
  "Welcome back, Zahraa": "مرحباً بعودتك، زهراء",
  "ADMIN DASHBOARD": "لوحة تحكم الأدمن",
  "Monitor your freelance platform and manage daily operations.": "تابعي منصة العمل الحر وأديري العمليات اليومية من مكان واحد.",
  "Total Users": "إجمالي المستخدمين",
  "Total Projects": "إجمالي المشاريع",
  "Total Revenue": "إجمالي الإيرادات",
  "Pending Reports": "البلاغات المعلقة",
  "Manage your administrator account and system preferences": "إدارة حساب الأدمن وتفضيلات النظام",
  "Admin Profile": "ملف الأدمن",
  "Personal account information": "معلومات الحساب الشخصية",
  "Security": "الأمان",
  "Update your password": "تحديث كلمة المرور",
  "System Notifications": "إشعارات النظام",
  "Choose which notifications the administrator receives": "اختاري الإشعارات التي يستلمها مدير النظام",
  "Full Name": "الاسم الكامل",
  "Email": "البريد الإلكتروني",
  "Phone": "رقم الهاتف",
  "Current Password": "كلمة المرور الحالية",
  "New Password": "كلمة المرور الجديدة",
  "Confirm Password": "تأكيد كلمة المرور",
  "Email Notifications": "إشعارات البريد الإلكتروني",
  "Receive general platform notifications.": "استلام إشعارات المنصة العامة.",
  "New Report Alerts": "تنبيهات البلاغات الجديدة",
  "Get notified when a complaint is submitted.": "استلام تنبيه عند إرسال شكوى جديدة.",
  "Payment Notifications": "إشعارات المدفوعات",
  "Receive updates about payments and commissions.": "استلام تحديثات المدفوعات والعمولات.",
  "Changes saved successfully": "تم حفظ التغييرات بنجاح",
};

export function translateText(text, isArabic) {
  if (!isArabic || text == null) return text;
  return dictionary[text] || text;
}

export function LanguageProvider({ children }) {
  const [isArabic, setIsArabic] = useState(() => localStorage.getItem("hub_admin_lang") !== "en");

  useEffect(() => {
    localStorage.setItem("hub_admin_lang", isArabic ? "ar" : "en");
    document.documentElement.lang = isArabic ? "ar" : "en";
    document.documentElement.dir = isArabic ? "rtl" : "ltr";
  }, [isArabic]);

  const value = useMemo(() => ({
    isArabic,
    toggleLanguage: () => setIsArabic((value) => !value),
    t: (text) => translateText(text, isArabic),
  }), [isArabic]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
