import React from 'react';
import { ArrowLeft, BriefcaseBusiness, Check, CircleDollarSign, ShieldCheck, Star } from 'lucide-react';
import { t } from '../freelance-i18n';
import { projects, img } from '../freelance-data';
import { Card, PageHeader, Stat } from '../components/freelance-UI';

export default function Dashboard({lang,notify}){
  return <>
    <PageHeader lang={lang} titleAr="لوحة التحكم" titleEn="Freelancer Dashboard" subAr="تابع دخلك، مشاريعك، عروضك، وأداء ملفك من مكان واحد." subEn="Track your income, projects, proposals, and profile performance in one place." action={<button className="primary" onClick={()=>notify(t(lang,'تم فتح قائمة المشاريع الجديدة','New project list opened'))}><BriefcaseBusiness size={16}/>{t(lang,'تصفح المشاريع','Browse Projects')}</button>}/>
    <div className="stats-grid"><Stat lang={lang} icon={CircleDollarSign} labelAr="الرصيد المتاح" labelEn="Available Balance" value="$4,250" delta="+14.2%"/><Stat lang={lang} icon={ShieldCheck} labelAr="المحجوز بالضمان" labelEn="In Escrow" value="$1,850" delta="+8.4%" tone="amber"/><Stat lang={lang} icon={BriefcaseBusiness} labelAr="العقود النشطة" labelEn="Active Contracts" value="3" delta="+1" tone="green"/><Stat lang={lang} icon={Star} labelAr="متوسط التقييم" labelEn="Average Rating" value="4.9 / 5" delta="+0.2" tone="purple"/></div>
    <div className="grid-2-1"><Card><div className="card-head"><div><h3>{t(lang,'الأداء والدخل','Performance & Income')}</h3><p>{t(lang,'تحليل النشاط خلال الفترة المحددة','Activity for the selected period')}</p></div><span className="badge-soft blue">30 {t(lang,'يوم','days')}</span></div><div className="chart"><div className="y-labels"><span>$2k</span><span>$1k</span><span>$0</span></div><div className="bars">{[45,64,50,76,59,68,58,83,72,88,77,91].map((h,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:`${h}%`}}/><span>{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i]}</span></div>)}</div></div></Card><Card><div className="card-head"><div><h3>{t(lang,'إكمال الملف','Profile Completion')}</h3><p>{t(lang,'حسّن ظهورك للعملاء','Improve your discoverability')}</p></div><span className="score">92%</span></div><div className="ring-wrap"><div className="ring"><div><b>92%</b><small>{t(lang,'مكتمل','Complete')}</small></div></div></div><div className="check-list"><div><Check size={14}/>{t(lang,'التخصص والمهارات','Specialty & skills')}</div><div><Check size={14}/>{t(lang,'4 أعمال في المحفظة','4 portfolio items')}</div><div><Check size={14}/>{t(lang,'وصف احترافي','Professional bio')}</div><button className="link-btn" onClick={()=>notify(t(lang,'تم فتح إعدادات الملف','Profile settings opened'))}>{t(lang,'إكمال الملف','Complete profile')} <ArrowLeft size={13}/></button></div></Card></div>
    <div className="grid-2"><Card><div className="card-head"><div><h3>{t(lang,'العقود النشطة','Active Contracts')}</h3><p>{t(lang,'العقود الحالية ومواعيد التسليم','Current contracts and delivery dates')}</p></div></div>{[['تصميم تجربة مستخدم لتطبيق العقارات','Property app UX redesign','Maryam Al-Saleh','$700','2026-09-28',68],['لوحة تحكم تحليلات SaaS','SaaS analytics dashboard','North Star','$520','2026-10-03',42],['تطوير Landing Page','Landing page development','Nexa Media','$320','2026-10-06',21]].map(r=><div className="contract-row" key={r[3]}><div className="avatar-text"><img src={img.clientA}/><div><b>{t(lang,r[0],r[1])}</b><small>{r[2]}</small></div></div><div><strong>{r[3]}</strong><small>{r[4]}</small></div><div className="progress"><div><span style={{width:`${r[5]}%`}}/></div><small>{r[5]}%</small></div></div>)}</Card><Card><div className="card-head"><div><h3>{t(lang,'مشاريع مقترحة','Recommended Projects')}</h3><p>{t(lang,'مطابقة مبنية على مهاراتك وأعمالك السابقة','Matched to your skills and portfolio')}</p></div></div>{projects.slice(0,3).map(p=><div className="recommend" key={p.id}><div className="match">{p.match}%<small>{t(lang,'مطابقة','Match')}</small></div><div className="recommend-main"><b>{t(lang,p.titleAr,p.titleEn)}</b><span>{p.budget} · {p.duration}</span><div className="tag-row">{p.skills.slice(0,2).map(s=><span className="tag" key={s}>{s}</span>)}</div></div></div>)}</Card></div>
  </>;
}
